# RomRaider2 packaged UI resources
brand.logo=/com/romraider2/ui/assets/branding/romraider2-logo-horizontal.png
splash.image=/com/romraider2/ui/assets/splash/romraider2-splash.png
app.icon.16=/com/romraider2/ui/assets/icons/app/romraider2-app-16.png
app.icon.20=/com/romraider2/ui/assets/icons/app/romraider2-app-20.png
app.icon.24=/com/romraider2/ui/assets/icons/app/romraider2-app-24.png
app.icon.32=/com/romraider2/ui/assets/icons/app/romraider2-app-32.png
app.icon.40=/com/romraider2/ui/assets/icons/app/romraider2-app-40.png
app.icon.48=/com/romraider2/ui/assets/icons/app/romraider2-app-48.png
app.icon.64=/com/romraider2/ui/assets/icons/app/romraider2-app-64.png
app.icon.128=/com/romraider2/ui/assets/icons/app/romraider2-app-128.png
app.icon.256=/com/romraider2/ui/assets/icons/app/romraider2-app-256.png
rom.icon.16=/com/romraider2/ui/assets/icons/files/romraider2-rom-16.png
rom.icon.24=/com/romraider2/ui/assets/icons/files/romraider2-rom-24.png
rom.icon.32=/com/romraider2/ui/assets/icons/files/romraider2-rom-32.png
rom.icon.48=/com/romraider2/ui/assets/icons/files/romraider2-rom-48.png
rom.icon.64=/com/romraider2/ui/assets/icons/files/romraider2-rom-64.png
rom.icon.128=/com/romraider2/ui/assets/icons/files/romraider2-rom-128.png
rom.icon.256=/com/romraider2/ui/assets/icons/files/romraider2-rom-256.png
